"""Check the registries: the closed sets of members that the concepts define.

A dictionary entry says what a `qiraah` is. A registry says which ten there
are. `validate.py` and `check_conformance.py` check entries; nothing checked
the members until this, which is to say the members were not checked.

    python3 tools/check_registries.py

What it checks:
  * every row has the columns the header declares
  * a code is unique inside its registry
  * a code that should be derived still derives from its Arabic (sections 4-8)
  * a code that should NOT be derived is a personal name, and says so
  * every reference — parent, rawi, surah, numbering — resolves
  * every `ref` names a source that exists in sources.yml
  * a member whose name shadows a concept's name is reported, not tolerated
    silently: it is the reason the registry index is namespaced
"""
import csv, glob, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import yaml
from translit import code_spelling

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGISTRIES = os.path.join(ROOT, "standards/terminology/registries")
CONCEPTS = os.path.join(ROOT, "standards/terminology/concepts")
SOURCES = os.path.join(ROOT, "standards/terminology/sources.yml")

# Whether a registry's codes are derived from its Arabic, and why not when they
# are not. A registry missing from here is a registry nobody decided about.
DERIVED = {
    "surahs": True,
    # Not derived: by section 14 these six take their parent's name. Deriving
    # العَدّ gives `add`, an English verb — the departure the decision record
    # argues for and check_conformance.py lists in DOCUMENTED.
    "ayah_numbering": False,
    "qiraat": False,   # people. A name carries no meaning for the derivation to
                       # keep, so deriving it invents a spelling nobody writes.
    "sajdah": None,    # positions, not names: the rows have no Arabic to derive
    "ayah_counts": None,  # numbers, generated by tools/extract_ayah_counts.py
}

# Registries whose rows carry data about concepts that already have entries,
# rather than members that have none. Their codes must BE concept codes, so a
# shared name is the point rather than a collision.
KEYED_BY_CONCEPT = {"ayah_numbering"}

# Columns that must resolve to a member of another registry, or to a concept.
REFERENCES = {
    ("qiraat", "parent"): ("qiraat", "code"),
    ("qiraat", "rawi"): ("qiraat", "code"),
    ("qiraat", "numbering"): ("concepts", None),
    ("ayah_numbering", "qiraat"): ("qiraat", "code"),
    ("sajdah", "surah"): ("surahs", "code"),
}


def read(path):
    """Rows of a registry, plus the header the last comment line declares."""
    header, rows = None, []
    for line in open(path, encoding="utf-8"):
        line = line.rstrip("\n")
        if line.startswith("#"):
            fields = line.lstrip("#").strip().split("\t")
            if len(fields) > 1:
                header = fields
            continue
        if not line.strip():
            continue
        rows.append(line.split("\t"))
    return header, rows


def load_concepts():
    out = set()
    for p in glob.glob(os.path.join(CONCEPTS, "*.yml")):
        out.add(yaml.safe_load(open(p, encoding="utf-8"))["concept"])
    return out


def check():
    problems, shadows, counts = [], [], {}
    concepts = load_concepts()
    sources = yaml.safe_load(open(SOURCES, encoding="utf-8")) or {}
    tables = {}

    for path in sorted(glob.glob(os.path.join(REGISTRIES, "*.tsv"))):
        name = os.path.basename(path)[:-4]
        header, rows = read(path)
        if not header:
            problems.append(f"{name}: no header line — the last comment line "
                            f"before the rows must name the columns, tab separated")
            continue
        tables[name] = (header, rows)
        counts[name] = len(rows)
        if name not in DERIVED:
            problems.append(f"{name}: not listed in DERIVED — say whether its "
                            f"codes are derived, and why not if they are not")

        for i, row in enumerate(rows, 1):
            if len(row) != len(header):
                problems.append(f"{name} row {i} ({row[0]}): {len(row)} columns, "
                                f"header declares {len(header)}")

    for name, (header, rows) in tables.items():
        col = {c: i for i, c in enumerate(header)}
        get = lambda row, c: row[col[c]].strip() if c in col and col[c] < len(row) else ""

        # a code is unique inside its own registry
        seen = {}
        key = "code" if "code" in col else None
        for i, row in enumerate(rows, 1):
            if not key:
                break
            code = get(row, key)
            if code in seen:
                problems.append(f"{name}: {code!r} used twice, rows {seen[code]} and {i}")
            seen[code] = i

        # sections 4-8, where the registry says the codes are derived
        if DERIVED.get(name) and "arabic" in col and key:
            for row in rows:
                code, arabic = get(row, key), get(row, "arabic")
                if not arabic:
                    continue
                try:
                    derived = code_spelling(arabic)
                except Exception as exc:
                    problems.append(f"{name}: cannot derive {code!r} from {arabic!r} — {exc}")
                    continue
                if derived != code:
                    problems.append(
                        f"{name}: code is {code!r}, {arabic!r} derives to {derived!r} "
                        f"— fix one of the two, or record the exception in "
                        f"data/established_spellings.tsv with its reason")

        # a reference the reader cannot follow is not a reference
        for (reg, column), (target, tcol) in REFERENCES.items():
            if reg != name or column not in col:
                continue
            if target == "concepts":
                valid = concepts
            else:
                th, tr = tables.get(target, ([], []))
                ti = th.index(tcol) if tcol in th else 0
                valid = {r[ti].strip() for r in tr}
            for row in rows:
                for value in filter(None, (v.strip() for v in get(row, column).split(","))):
                    if value not in valid:
                        problems.append(f"{name}: {get(row, key or header[0])!r} points "
                                        f"{column} at {value!r}, which is not in {target}")

        # the counts table is only as good as its reconciliation
        if name == "ayah_counts":
            for school, want in (("kufi", 6236), ("basri", 6204)):
                if school in col:
                    got = sum(int(get(r, school)) for r in rows if get(r, school).isdigit())
                    if got != want:
                        problems.append(f"{name}: {school} sums to {got}, and al-Dani "
                                        f"states {want} — rerun tools/extract_ayah_counts.py")
            if len(rows) != 114:
                problems.append(f"{name}: {len(rows)} rows, expected 114")

        # a sajdah must fall inside its own surah, by the verified counts
        if name == "sajdah" and "ayah_counts" in tables:
            ch, cr = tables["ayah_counts"]
            kufi = {int(r[0]): int(r[ch.index("kufi")]) for r in cr}
            sh, sr = tables["surahs"]
            snum = {r[sh.index("code")]: int(r[sh.index("number")]) for r in sr}
            for row in rows:
                ref = get(row, "ayah")
                sur = get(row, "surah")
                if ":" not in ref: continue
                s_no, a_no = (int(x) for x in ref.split(":"))
                if snum.get(sur) != s_no:
                    problems.append(f"{name}: {ref} is given as {sur!r}, which is "
                                    f"surah {snum.get(sur)}")
                elif a_no > kufi.get(s_no, 0):
                    problems.append(f"{name}: {ref} is outside its surah — "
                                    f"surah {s_no} has {kufi.get(s_no)} ayahs")

        # section 28 — a claim with no source behind it
        if "ref" in col:
            for row in rows:
                ref = get(row, "ref")
                if not ref:
                    problems.append(f"{name}: {get(row, key or header[0])!r} has no ref")
                elif ref.split()[0] not in sources:
                    problems.append(f"{name}: {get(row, key or header[0])!r} cites "
                                    f"{ref.split()[0]!r}, which is not in sources.yml")

        # a member that shadows a concept: recorded, because it is exactly why
        # the registry index is namespaced rather than flat
        if key:
            for row in rows:
                code = get(row, key)
                if name in KEYED_BY_CONCEPT:
                    if code not in concepts:
                        problems.append(f"{name}: {code!r} names no concept, and this "
                                        f"registry carries data about concepts")
                elif code in concepts:
                    shadows.append(f"{name}:{code} shadows the concept "
                                   f"of the same name")

    return problems, shadows, counts


# Concepts whose members are a closed set that has not been written down yet.
# Listed so the gap is reported on every run instead of being forgotten.
OPEN_GAPS = {
    "tariq": "the turuq of the ten readings — see the note at the head of "
             "registries/qiraat.tsv for what was tried and why it was not kept",
}


def main():
    problems, shadows, counts = check()
    total = sum(counts.values())
    if problems:
        print(f"{len(problems)} problems across {total} members:")
        for p in problems:
            print(f"  {p}")
    else:
        print(f"ok — {total} members in {len(counts)} registries "
              f"({', '.join(f'{k} {v}' for k, v in sorted(counts.items()))})")
    if shadows:
        print(f"\n{len(shadows)} members share a name with a concept. This is not an "
              f"error: the\nregistry index is namespaced for exactly this reason, and "
              f"the bare name\nkeeps resolving to the concept.")
        for s in shadows:
            print(f"  {s}")
    if OPEN_GAPS:
        print(f"\n{len(OPEN_GAPS)} closed sets still have no registry:")
        for concept, why in sorted(OPEN_GAPS.items()):
            print(f"  {concept}: {why}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
