#!/usr/bin/env python3
"""Write content/glossary.json: the short glossary the site renders, from the dictionary.

The site used to keep its own list of terms. It now reads this file, so a term is
defined once, in standards/terminology/concepts/<code>.yml, and the site shows the
entry's `display` form. Add a term by adding its code to TERMS; nothing is typed here.
"""
import datetime
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONCEPTS = ROOT / "standards" / "terminology" / "concepts"
OUT = ROOT / "content" / "glossary.json"

# The Quranic concepts the site's docs name on first use. Order is display order.
TERMS = [
    "mushaf", "surah", "ayah", "basmalah", "qiraah", "riwayah", "rawi",
    "rasm", "harakah", "shaddah", "waqf", "ayah_mark", "tajwid", "tajwid_ruling",
]


def one(code: str) -> dict:
    path = CONCEPTS / f"{code}.yml"
    if not path.exists():
        sys.exit(f"generate_glossary.py: no concept file for {code!r}")
    c = yaml.safe_load(path.read_text(encoding="utf8"))
    names = c["names"]
    arabic = names.get("arabic", {})
    return {
        "id": code,
        "display": names.get("display", code),
        "arabic": arabic.get("singular") or arabic.get("vocalized", ""),
        "explain": " ".join(str(c.get("definition_en", "")).split()),
        "forDevs": " ".join(str(c.get("purpose_en", "")).split()),
        "status": c.get("status", "draft"),
    }


def main() -> int:
    terms = [one(code) for code in TERMS]
    missing = [t["id"] for t in terms if not t["explain"] or not t["forDevs"]]
    if missing:
        sys.exit(f"generate_glossary.py: entries without definition_en or purpose_en: {missing}")
    doc = {
        "generated": datetime.date.today().isoformat(),
        "source": "quran-ws/docs standards/terminology/concepts",
        "note": "Generated by tools/generate_glossary.py. Edit the concept file, not this one.",
        "terms": terms,
    }
    text = json.dumps(doc, ensure_ascii=False, indent=2) + "\n"
    if "--check" in sys.argv:
        current = OUT.read_text(encoding="utf8") if OUT.exists() else ""
        # `generated` moves daily; compare everything else
        strip = lambda s: "\n".join(l for l in s.splitlines() if '"generated"' not in l)
        if strip(current) != strip(text):
            sys.exit("content/glossary.json is stale; run python3 tools/generate_glossary.py")
        print("glossary current")
        return 0
    if OUT.exists() and OUT.read_text(encoding="utf8").split('"source"')[1:] == text.split('"source"')[1:]:
        print(f"{len(terms)} terms, unchanged")
        return 0
    OUT.write_text(text, encoding="utf8")
    print(f"{len(terms)} terms written to content/glossary.json")
    return 0


if __name__ == "__main__":
    sys.exit(main())
