"""Build the agent skill: the standard and its dictionary, packaged for an AI.

Section 29 says the human-readable documents are output from the machine-readable
source. An agent reading a codebase needs the same thing in a third shape: the
rules as prose it can follow, the dictionary as data it can resolve names
against, and scripts that answer "is this name canonical" without a model having
to guess.

    python3 tools/generate_skill.py

Everything under skills/quranic-terminology/ is written by this script. The
prose it does not generate — the standard, the decision record, the dictionary —
is copied from content/en, so the skill cannot state a rule the standard does
not.
"""
import glob, json, os, re, shutil, subprocess, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import yaml
from translit import code_spelling

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TERMS = os.path.join(ROOT, "standards/terminology")
CONCEPTS = os.path.join(TERMS, "concepts")
TEMPLATE = os.path.join(ROOT, "tools/skill_template")
OUT = os.path.join(ROOT, "skills/quranic-terminology")

# The prose the skill hands to a reader, copied rather than restated.
REFERENCES = [
    ("content/en/03-terminology/standard.md", "standard.md"),
    ("content/en/03-terminology/dictionary.md", "dictionary.md"),
    ("content/en/03-terminology/decisions.md", "decisions.md"),
]

FIELDS = ("kind", "category", "origin", "tier", "status", "plural", "parent",
          "registry", "definition_en", "purpose_en", "boundaries_en", "note_en",
          "alternative_spellings", "english_glosses", "deprecated", "related",
          "symbol", "mark_family")

DERIVED_PLURAL = re.compile(r"^[a-z][a-z_]*[aiu][a-z_]*$")


def load():
    out = []
    for path in sorted(glob.glob(os.path.join(CONCEPTS, "*.yml"))):
        out.append(yaml.safe_load(open(path, encoding="utf-8")))
    return out


def arabic_plurals(entry):
    """The Arabic plural as it would be spelled in code, when it derives.

    Section 11 forbids it as a name, so the audit needs to recognise it. An
    unvocalized plural cannot be derived, and a guess would be worse than a
    gap, so it is left out.
    """
    plural = (entry["names"].get("arabic") or {}).get("plural")
    if not plural:
        return []
    try:
        derived = code_spelling(plural)
    except Exception:
        return []
    return [derived] if DERIVED_PLURAL.match(derived) else []


REPO = "quran-ws/guidelines"   # the fallback when there is no git remote to read


def version():
    """The commit this snapshot was built from, so the skill can tell it is stale.

    `scripts/update_check.py` compares it against the same path on GitHub. A
    build outside a git checkout still produces a skill; it just cannot say
    which commit it came from.
    """
    def git(*args):
        try:
            return subprocess.run(("git", "-C", ROOT) + args, capture_output=True,
                                  text=True, check=True).stdout.strip()
        except (OSError, subprocess.CalledProcessError):
            return None

    commit = git("rev-parse", "HEAD")
    remote = git("remote", "get-url", "origin") or ""
    match = re.search(r"github\.com[:/](.+?)(?:\.git)?$", remote)
    return {
        "repo": match.group(1) if match else REPO,
        "commit": commit[:12] if commit else None,
        "date": git("log", "-1", "--format=%cI", "--", "standards/terminology"),
        "dirty": bool(git("status", "--porcelain", "--", "standards/terminology")) or None,
    }


def clean(value):
    """Folded YAML keeps a trailing newline; JSON should not carry it."""
    if isinstance(value, str):
        return value.strip()
    if isinstance(value, list):
        return [clean(v) for v in value]
    return value


def terminology(entries):
    concepts = {}
    for e in entries:
        names = e["names"]
        item = {"code": names["code"], "display": names.get("display"),
                "arabic": (names.get("arabic") or {}).get("vocalized"),
                "transliteration": names.get("transliteration")}
        for field in FIELDS:
            if e.get(field):
                item[field] = e[field]
        plurals = arabic_plurals(e)
        if plurals:
            item["arabic_plurals"] = plurals
        concepts[e["concept"]] = {k: clean(v) for k, v in item.items() if v is not None}

    aliases = json.load(open(os.path.join(TERMS, "aliases.json"), encoding="utf-8"))
    members = json.load(open(os.path.join(TERMS, "registry_aliases.json"), encoding="utf-8"))
    return {
        "standard": "Quranic Software Terminology Standard",
        "version": version(),
        "source": "https://github.com/quran-ws/guidelines",
        "note": "Generated by tools/generate_skill.py. Edit the concept files, not this.",
        "concepts": concepts,
        "aliases": aliases,
        "registry_members": members,
    }


SPELLING_TABLES = ("letter_names.tsv", "established_spellings.tsv", "general_words.tsv")
# translit.py finds its tables relative to the repository. Inside the skill they
# sit next to the script, so the copy is repointed rather than duplicated by hand.
TABLE_PATH = re.compile(
    r"_os\.path\.join\(_os\.path\.dirname\(_os\.path\.dirname\(_os\.path\.abspath\("
    r"__file__\)\)\),\s*\n?\s*\"standards/terminology/data/([\w.]+)\"\)")


def write_speller():
    """Copy the derivation itself, so the skill spells names by the same function."""
    source = open(os.path.join(ROOT, "tools/translit.py"), encoding="utf-8").read()
    patched, count = TABLE_PATH.subn(r'_os.path.join(_TABLES, "\1")', source)
    if count != len(SPELLING_TABLES):
        raise SystemExit(f"translit.py has {count} table paths, expected {len(SPELLING_TABLES)} "
                         f"— update TABLE_PATH in tools/generate_skill.py")
    header = ('_TABLES = _os.path.join(_os.path.dirname(_os.path.dirname(\n'
              '    _os.path.abspath(__file__))), "data", "spelling")\n')
    marker = "\nHARAKAT"
    patched = patched.replace(marker, "\n" + header + marker, 1)
    tables = os.path.join(OUT, "data/spelling")
    os.makedirs(tables, exist_ok=True)
    for name in SPELLING_TABLES:
        shutil.copy(os.path.join(TERMS, "data", name), os.path.join(tables, name))
    open(os.path.join(OUT, "scripts/spell.py"), "w", encoding="utf-8").write(patched)


def strip_frontmatter(text):
    """The pages are Starlight pages; the skill wants the prose."""
    if text.startswith("---"):
        end = text.index("\n---", 3) + len("\n---")
        head = text[:end]
        title = re.search(r"^title: (.+)$", head, re.M)
        text = text[end:].lstrip("\n")
        if title:
            text = f"# {title.group(1).strip()}\n\n{text}"
    def aside(match):
        title, body = match.group(1), match.group(2).strip().splitlines()
        lines = [f"> **{title}**", ">"] if title else []
        return "\n".join(lines + [f"> {line}".rstrip() for line in body]) + "\n"

    return re.sub(r"^:::\w+(?:\[([^\]]*)\])?\s*\n(.*?)^:::\s*$",
                  aside, text, flags=re.M | re.S)


def fill(text, values):
    for key, value in values.items():
        text = text.replace("{{" + key + "}}", str(value))
    left = re.findall(r"\{\{(\w+)\}\}", text)
    if left:
        raise SystemExit(f"the template has placeholders nothing filled: {sorted(set(left))}")
    return text


def main():
    entries = load()
    data = terminology(entries)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(os.path.join(OUT, "data/registries"))
    os.makedirs(os.path.join(OUT, "references"))
    shutil.copytree(os.path.join(TEMPLATE, "scripts"), os.path.join(OUT, "scripts"))

    json.dump(data, open(os.path.join(OUT, "data/terminology.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1, sort_keys=True)
    for tsv in sorted(glob.glob(os.path.join(TERMS, "registries/*.tsv"))):
        shutil.copy(tsv, os.path.join(OUT, "data/registries", os.path.basename(tsv)))
    shutil.copy(os.path.join(TERMS, "schema.json"), os.path.join(OUT, "data/schema.json"))
    write_speller()

    for source, name in REFERENCES:
        text = strip_frontmatter(open(os.path.join(ROOT, source), encoding="utf-8").read())
        open(os.path.join(OUT, "references", name), "w", encoding="utf-8").write(text)

    categories = sorted({e["category"] for e in entries})
    registries = sorted(os.path.basename(p)[:-4]
                        for p in glob.glob(os.path.join(TERMS, "registries/*.tsv")))
    skill = fill(open(os.path.join(TEMPLATE, "SKILL.md"), encoding="utf-8").read(), {
        "ENTRIES": len(entries),
        "SPELLINGS": len(data["aliases"]),
        "CATEGORIES": ", ".join(f"`{c}`" for c in categories),
        "REGISTRIES": ", ".join(f"`{r}`" for r in registries),
        "ADOPTED": sum(1 for e in entries if e["status"] == "adopted"),
        "DRAFT": sum(1 for e in entries if e["status"] == "draft"),
        "COMMIT": data["version"]["commit"] or "unknown",
        "REPO": REPO,
    })
    open(os.path.join(OUT, "SKILL.md"), "w", encoding="utf-8").write(skill)

    stamp = data["version"]
    print(f"skill written to {os.path.relpath(OUT, ROOT)}/ — "
          f"{len(entries)} entries, {len(data['aliases'])} spellings, "
          f"{len(registries)} registries, built from "
          f"{stamp['repo']}@{stamp['commit'] or 'unknown'}"
          f"{' (with uncommitted changes)' if stamp.get('dirty') else ''}")


if __name__ == "__main__":
    main()
